### ISSUE TITLE
[Chart 2D Editor] Disabling 'Use array indices from Y array'

### ISSUE THREAD

**Issue by dosintsev** [viennamos/viennamos-dev#1]
If 'quantity' is selected for the X-axis, uncheck 'Enable all' for the Y-axis leads to disable 'Use array indices from Y array' radio button.

To reproduce:
1. Run SiSpin module simulations
2. Add 2D Chart, open 2D Chart Editor
3. Select 'quantity' for the X-axis
4. Uncheck 'Enable all' for Y-axis

![image](https://f.cloud.github.com/assets/4905773/735590/e16737c4-e2f8-11e2-8026-1d88c7745804.png)

**Comment by viennamos** [comment]
Thanks! - fixed in commit 06b805191f9b25aa8d7f84526c565e230d569606
