### ISSUE TITLE
[API] Add a signal on table remove

### ISSUE THREAD

**Issue by dosintsev** [viennamos/viennamos-dev#12]
In order to keep a compliance of the list of tables stored in the central storage of ViennaMOS and in module all modifications of the list should emit a signal.

**Comment by JosefWeinbub** [comment]
thanks!
the multiview object (available in each ViennaMOS module) now offers the signal 'tableRemoved(std::size_t table_index)' -> the table index is the obvious table ID of the removed table.
connect to this signal in the 'preprocess()' method, and not in the module's c'tor, as the datastructures are not instantiated at the time the c'tor is processed.
