### ISSUE TITLE
[Chart 2D Editor] Wrong curve after label renaming

### ISSUE THREAD

**Issue by dosintsev** [viennamos/viennamos-dev#14]
The problem occurs if the new name of the label is equal to one of the Y-axis labels.

To reproduce:
1.Run the following simulation 
[General]
Domain=1
Kx=0.1
Ky=0.1
ShearStrain=0
Solver=1
Thickness=3.3
XStep=0.01
Xmax=1.5
Xmin=0
YStep=0
Ymax=0
Ymin=0
2. Select exy Quantity for X-axis, Splitting_2 for Y-axis and Apply
3. Change Label of the curve to Energy_1, Apply

**Comment by JosefWeinbub** [comment]
Thanks!

It seems that VTK does require the quantitiy labels to be unique, thus I have added an error message which notifies
the user about this fact and ultimately prohibits the visualization of a wrong quantity. 

Is it really required to rename a label of a quantity to an already available quantity? (non-uniqueness)

**Comment by dosintsev** [comment]
I am happy with the current implementation, the main thing is to avoid of unexpected curves. But another problem appears - I wanted to rename label Splitting_2 to Splitting_1 which already exists, an error message appears, it is ok, but I was not able to rename Splitting_2 back to Splitting_2 :)

**Comment by JosefWeinbub** [comment]
got it, I have added a mechanism which resets the label to the original label if an error occured.

Closed
