### ISSUE TITLE
[Chart 2D Editor] Check/Uncheck 'Enable all' puts 'Quantity' to default value

### ISSUE THREAD

**Issue by dosintsev** [viennamos/viennamos-dev#2]
To reproduce:
1. Run SiSpin module simulations
2. Add 2D Chart, open 2D Chart Editor
3. Select 'quantity' for the X-axis
4. Chage selection to 'Splitting_1'
4. Uncheck 'Enable all' for Y-axis

**Comment by viennamos** [comment]
Thanks! - fixed in commit 142b0a3f6126ec444e2638908be395dcc0ac4df9
