### ISSUE TITLE
copy quantity function should automatically conduct a quantity cell transfer if required

### ISSUE THREAD

**Issue by JosefWeinbub** [viennamos/viennamos-dev#21]
Option 1: 
explicitly mention the source and target cells 

> viennamos::copy<VertexType, VertexType>(device, source_acc, target_acc);
> viennamos::copy<VertexType, CellType>(device, source_acc, target_acc);

Option 2:
setup a accessor concept which holds the cell level so copy can access it

> viennamos::copy(device, source_vertex_acc, target_vertex_acc);
> viennamos::copy(device, source_vertex_acc, target_cell_acc);

**Comment by karlrupp** [comment]
I'm afraid that an automatic conversion will bite you sooner or later, because you will also want to specify the interpolation function (arithmetic averaging? geometric averaging? other?) sooner or later.

**Comment by JosefWeinbub** [comment]
good point
