### ISSUE TITLE
git subtree making things difficult

### ISSUE THREAD

**Issue by lutherthecat** [viennamos/viennamos-dev#23]
What version of git are you using with which os?  Trying to merge with a version of git without subtree is difficult.

**Comment by JosefWeinbub** [comment]
Hi, my client version is 1.8.1.5 on Linux 64bit.
We are currently testing the feasibility of the subtree mechanism to include some other required git-based projects.
Could you please describe exactly what you want to do and what exactly doesn't work? also, what git version and OS are you on?
Thanks!

**Comment by lutherthecat** [comment]
"Ubuntu 12.04.3 LTS", x86_64
git version 1.7.9.5

Your project is already using the subtree mechanism, and it is causing problems with non-subtree versions of git.

This version of git doesn't have subtree, but it is able to clone from your viennamos repository.  When I try to merge from your upstream repository to my fork, it results in a lot of conflicts having to do with the external directories having the same name as files.

Here are the messages I'm receiving:
viennamos-dev> git merge upstream
error: 'external/ViennaCL' appears as both a file and as a directory
error: external/ViennaCL: cannot drop to stage #0
error: 'merge' is not possible because you have unmerged files.
hint: Fix them up in the work tree,
hint: and then use 'git add/rm <file>' as
hint: appropriate to mark resolution and make a commit,
hint: or use 'git commit -a'.
fatal: Exiting because of an unresolved conflict.

I'm on the fence right now about how much effort I want to put into  this.  I certainly don't want to have to compile a new version of git for all the platforms I'm working on.

**Comment by lutherthecat** [comment]
It looks like subtree is actually an older feature.  My version of git doesn't recognize the "git subtree" syntax in your update_subtrees.sh script.

In my projects, I've used submodule instead of subtree. submodule can be a nice alternative, since the modules are kept separate from the repository tree.

**Comment by lutherthecat** [comment]
sorry, I accidently closed the issue.

**Comment by JosefWeinbub** [comment]
submodule is indeed an alternative, but there are several drawbacks and this is the reason I went for subtree [1].
It seems that subtree is supported from git version 1.7.11, so yes, your version is indeed not supported.
I will look into alternatives. 

[1] http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/

**Comment by lutherthecat** [comment]
Whatever your decision is is fine.  I'll be evaluating your program and seeing what the best way to contribute might be.

**Comment by JosefWeinbub** [comment]
Great! Thanks for your interest. ViennaMOS is still a prototype, no documentation is available right now - primarily due to lack of resources. But I can push it to the top of my todo list if I know you are interested. 
Would you be interested to implement a module for Genius-TCAD-Open, which you are contributing to?
I should be able to come up with a manual describing 'how to implement a module' in a short period of time, probably within the next week. If this works for you?!

**Comment by lutherthecat** [comment]
All I really did with Genius was to get it to work with CMake and report a bug in their cgns reader.  They already have their own Visual TCAD solution.

Let me think about a possible project.  I really wouldn't be able to start a new project until sometime early next year.

**Comment by JosefWeinbub** [comment]
Got it. Anyway, it is a good idea to come up with a documentation for 'adding a module' soon. 
By the way, are the library versions VTK 5.10.\* and Qt 4.8.\* fine with you? I haven't found the time yet to make it backwards and forwards compatible. VTK 6.0.\* is on my todo list, Qt 5 not so much as VTK 6.0.0 (current version) doesn't support Qt 5 at the moment -> so I have to wait here.
I can invest some time in ViennaMOS in the upcoming weeks. I will keep you posted on the progress.

**Comment by lutherthecat** [comment]
The application builds with stock ubuntu 12.04 x86_64 packages.  I'd only change your README.md to suggest:

## for debugging symbols

cmake -DCMAKE_BUILD_TYPE=DEBUG ..
or

## for optimized build

cmake -DCMAKE_BUILD_TYPE=RELEASE ..

I'm closing the ticket.  But feel free to contact me via github messaging.
