### ISSUE TITLE
[Chart 2D] Wrong X-axis for second graph

### ISSUE THREAD

**Issue by dosintsev** [viennamos/viennamos-dev#3]
To reproduce:
1. Run SiSpin
 [General]
Domain=0
Solver=1
Xmin=1
Xmax=2
Xstep=0.1
Ymin=0
Ymax=0
Ystep=0
Thickness=0
ShearStrain=0
Kx=0.1
Ky=0.1
2. Run SiSpin for Xmax=3
3. Open 2D Chart Editor
4. Select Quantity=thick, Yaxis=Splitting for both experiments

It seems that the second graph uses array indices as X-axis values

![image](https://f.cloud.github.com/assets/4905773/735675/d7ff7306-e2fb-11e2-951d-84cd4e97578e.png)

**Comment by viennamos** [comment]
Thanks! fixed.
