### ISSUE TITLE
[Chart 2D] Save XY-axis properties after adding a new table

### ISSUE THREAD

**Issue by dosintsev** [viennamos/viennamos-dev#4]
1. Do not reset settings for existing graphs (tables) when a new one is added
2. Apply XY-axis settings of the last graph to a new added graph (table)

**Comment by viennamos** [comment]
Thanks!
I partially implemented the functionality, meaning, the settings of the 'old' tables are kept, whereas when a new table is added, it is equipped with default parameters. I think this makes sense, as a new table might have completely different columns. If in fact the new table has the same column, the user can simply forward the parameters from a previous table to the new ones with the ' adopt to all' mechanism.

I hope this is reasonable, let me know if not. For now I am closing this.
