### ISSUE TITLE
[API] Couple params set and data set

### ISSUE THREAD

**Issue by dosintsev** [viennamos/viennamos-dev#7]
Currently it is possible to add a table to a multiview object, but the parameters that were used to get this data are not saved. It would be nice to be able to add a 'tag' to the data table. Tag could just be of QObject type so user can save what ever he wants from simple QString to QSettings or custom object.

**Comment by JosefWeinbub** [comment]
thanks!

although the feature request
    was related to a 'object meta info storage approach', we followed
    a different approach where we guarantee that the table id remains sane.

```
as the user can also access all tables, and has access to the table ids,
the user can keep track of changes in the table storage
```

let's see how this works out for us ..
